services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    pull_policy: always
    tty: true
    restart: unless-stopped
    
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - '8000:8000'
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
      
  frontend:
    build: ./frontend
    ports:
      - '3000:4173'
    depends_on:
      - backend

volumes:
  ollama_data:
